# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/om3/cusl4-oflute/trunk

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/om3/cusl4-oflute/trunk

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/om3/cusl4-oflute/trunk/CMakeFiles /home/om3/cusl4-oflute/trunk/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/om3/cusl4-oflute/trunk/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named programa

# Build rule for target.
programa: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 programa
.PHONY : programa

# fast build rule for target.
programa/fast:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/build
.PHONY : programa/fast

FFT.o: FFT.cpp.o
.PHONY : FFT.o

# target to build an object file
FFT.cpp.o:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/FFT.cpp.o
.PHONY : FFT.cpp.o

FFT.i: FFT.cpp.i
.PHONY : FFT.i

# target to preprocess a source file
FFT.cpp.i:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/FFT.cpp.i
.PHONY : FFT.cpp.i

FFT.s: FFT.cpp.s
.PHONY : FFT.s

# target to generate assembly for a file
FFT.cpp.s:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/FFT.cpp.s
.PHONY : FFT.cpp.s

analizador.o: analizador.cpp.o
.PHONY : analizador.o

# target to build an object file
analizador.cpp.o:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/analizador.cpp.o
.PHONY : analizador.cpp.o

analizador.i: analizador.cpp.i
.PHONY : analizador.i

# target to preprocess a source file
analizador.cpp.i:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/analizador.cpp.i
.PHONY : analizador.cpp.i

analizador.s: analizador.cpp.s
.PHONY : analizador.s

# target to generate assembly for a file
analizador.cpp.s:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/analizador.cpp.s
.PHONY : analizador.cpp.s

animacion.o: animacion.cpp.o
.PHONY : animacion.o

# target to build an object file
animacion.cpp.o:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/animacion.cpp.o
.PHONY : animacion.cpp.o

animacion.i: animacion.cpp.i
.PHONY : animacion.i

# target to preprocess a source file
animacion.cpp.i:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/animacion.cpp.i
.PHONY : animacion.cpp.i

animacion.s: animacion.cpp.s
.PHONY : animacion.s

# target to generate assembly for a file
animacion.cpp.s:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/animacion.cpp.s
.PHONY : animacion.cpp.s

colores.o: colores.cpp.o
.PHONY : colores.o

# target to build an object file
colores.cpp.o:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/colores.cpp.o
.PHONY : colores.cpp.o

colores.i: colores.cpp.i
.PHONY : colores.i

# target to preprocess a source file
colores.cpp.i:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/colores.cpp.i
.PHONY : colores.cpp.i

colores.s: colores.cpp.s
.PHONY : colores.s

# target to generate assembly for a file
colores.cpp.s:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/colores.cpp.s
.PHONY : colores.cpp.s

controlSonido.o: controlSonido.cpp.o
.PHONY : controlSonido.o

# target to build an object file
controlSonido.cpp.o:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/controlSonido.cpp.o
.PHONY : controlSonido.cpp.o

controlSonido.i: controlSonido.cpp.i
.PHONY : controlSonido.i

# target to preprocess a source file
controlSonido.cpp.i:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/controlSonido.cpp.i
.PHONY : controlSonido.cpp.i

controlSonido.s: controlSonido.cpp.s
.PHONY : controlSonido.s

# target to generate assembly for a file
controlSonido.cpp.s:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/controlSonido.cpp.s
.PHONY : controlSonido.cpp.s

estadoAnalizador.o: estadoAnalizador.cpp.o
.PHONY : estadoAnalizador.o

# target to build an object file
estadoAnalizador.cpp.o:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/estadoAnalizador.cpp.o
.PHONY : estadoAnalizador.cpp.o

estadoAnalizador.i: estadoAnalizador.cpp.i
.PHONY : estadoAnalizador.i

# target to preprocess a source file
estadoAnalizador.cpp.i:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/estadoAnalizador.cpp.i
.PHONY : estadoAnalizador.cpp.i

estadoAnalizador.s: estadoAnalizador.cpp.s
.PHONY : estadoAnalizador.s

# target to generate assembly for a file
estadoAnalizador.cpp.s:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/estadoAnalizador.cpp.s
.PHONY : estadoAnalizador.cpp.s

estadoImagenFija.o: estadoImagenFija.cpp.o
.PHONY : estadoImagenFija.o

# target to build an object file
estadoImagenFija.cpp.o:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/estadoImagenFija.cpp.o
.PHONY : estadoImagenFija.cpp.o

estadoImagenFija.i: estadoImagenFija.cpp.i
.PHONY : estadoImagenFija.i

# target to preprocess a source file
estadoImagenFija.cpp.i:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/estadoImagenFija.cpp.i
.PHONY : estadoImagenFija.cpp.i

estadoImagenFija.s: estadoImagenFija.cpp.s
.PHONY : estadoImagenFija.s

# target to generate assembly for a file
estadoImagenFija.cpp.s:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/estadoImagenFija.cpp.s
.PHONY : estadoImagenFija.cpp.s

estadoMenu.o: estadoMenu.cpp.o
.PHONY : estadoMenu.o

# target to build an object file
estadoMenu.cpp.o:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/estadoMenu.cpp.o
.PHONY : estadoMenu.cpp.o

estadoMenu.i: estadoMenu.cpp.i
.PHONY : estadoMenu.i

# target to preprocess a source file
estadoMenu.cpp.i:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/estadoMenu.cpp.i
.PHONY : estadoMenu.cpp.i

estadoMenu.s: estadoMenu.cpp.s
.PHONY : estadoMenu.s

# target to generate assembly for a file
estadoMenu.cpp.s:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/estadoMenu.cpp.s
.PHONY : estadoMenu.cpp.s

juego.o: juego.cpp.o
.PHONY : juego.o

# target to build an object file
juego.cpp.o:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/juego.cpp.o
.PHONY : juego.cpp.o

juego.i: juego.cpp.i
.PHONY : juego.i

# target to preprocess a source file
juego.cpp.i:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/juego.cpp.i
.PHONY : juego.cpp.i

juego.s: juego.cpp.s
.PHONY : juego.s

# target to generate assembly for a file
juego.cpp.s:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/juego.cpp.s
.PHONY : juego.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/programa.dir/build.make CMakeFiles/programa.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... programa"
	@echo "... rebuild_cache"
	@echo "... FFT.o"
	@echo "... FFT.i"
	@echo "... FFT.s"
	@echo "... analizador.o"
	@echo "... analizador.i"
	@echo "... analizador.s"
	@echo "... animacion.o"
	@echo "... animacion.i"
	@echo "... animacion.s"
	@echo "... colores.o"
	@echo "... colores.i"
	@echo "... colores.s"
	@echo "... controlSonido.o"
	@echo "... controlSonido.i"
	@echo "... controlSonido.s"
	@echo "... estadoAnalizador.o"
	@echo "... estadoAnalizador.i"
	@echo "... estadoAnalizador.s"
	@echo "... estadoImagenFija.o"
	@echo "... estadoImagenFija.i"
	@echo "... estadoImagenFija.s"
	@echo "... estadoMenu.o"
	@echo "... estadoMenu.i"
	@echo "... estadoMenu.s"
	@echo "... juego.o"
	@echo "... juego.i"
	@echo "... juego.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

